[
  { name: 'AddMeS', url: 'https://addmes.io/', icon: 'fas fa-user-plus', description: 'Plataforma para encontrar y agregar contactos en redes sociales' },
  { name: 'WhatsApp Fake Chat', url: 'https://www.fakewhats.com/generator', icon: 'fab fa-whatsapp', description: 'Generador de chats falsos de WhatsApp' },
  { name: 'Analizador de Perfiles', url: 'https://inflact.com/tools/profile-analyzer/', icon: 'fas fa-user-circle', description: 'Herramienta para analizar perfiles de Instagram' },
  { name: 'AnalyzeID', url: 'https://analyzeid.com/', icon: 'fas fa-id-card', description: 'Análisis de identidades en línea' },
  { name: 'sowsearch', url: 'https://www.sowsearch.info/', icon: 'fas fa-search', description: 'Motor de búsqueda para redes sociales' },
  { name: 'Aplicaciones de Facebook', url: 'https://khalil-shreateh.com/khalil.shtml/social_applications/facebook-applications/', icon: 'fab fa-facebook', description: 'Colección de aplicaciones para Facebook' },
  { name: 'BirdHunt', url: 'https://birdhunt.huntintel.io/', icon: 'fas fa-dove', description: 'Herramienta de OSINT para Twitter' },
  { name: 'Búsqueda de Recuperación de Facebook', url: 'https://www.facebook.com/login/identify?ctx=recover', icon: 'fab fa-facebook', description: 'Herramienta de recuperación de cuentas de Facebook' },
  { name: 'ChatBottle: Telegram', url: 'https://chatbottle.co/bots/telegram', icon: 'fab fa-telegram', description: 'Buscador de bots de Telegram' },
  { name: 'Commit-stream', url: 'https://github.com/x1sec/commit-stream', icon: 'fab fa-github', description: 'Herramienta para rastrear commits en GitHub' },
  { name: 'CrossLinked', url: 'https://github.com/m8sec/CrossLinked', icon: 'fab fa-linkedin', description: 'Herramienta para buscar perfiles de LinkedIn' },
  { name: 'Deleted Tweet Finder', url: 'https://cache.digitaldigging.org/', icon: 'fab fa-twitter', description: 'Buscador de tweets eliminados' },
  { name: 'Digital Privacy', url: 'https://github.com/ffffffff0x/Digital-Privacy', icon: 'fas fa-shield-alt', description: 'Recursos para privacidad digital' },
  { name: 'Disboard', url: 'https://disboard.org/', icon: 'fab fa-discord', description: 'Directorio de servidores de Discord' },
  { name: 'Discord.name', url: 'https://discord.name/', icon: 'fab fa-discord', description: 'Buscador de nombres de usuario en Discord' },
  { name: 'DiscordOSINT', url: 'https://github.com/husseinmuhaisen/DiscordOSINT?tab=readme-ov-file#-discord-search-syntax-', icon: 'fab fa-discord', description: 'Herramienta OSINT para Discord' },
  { name: 'DownAlbum', url: 'https://chrome.google.com/webstore/detail/downalbum/cgjnhhjpfcdhbhlcmmjppicjmgfkppok', icon: 'fas fa-download', description: 'Extensión para descargar álbumes de redes sociales' },
  { name: 'Download Twitter Data', url: 'https://www.twtdata.com/', icon: 'fab fa-twitter', description: 'Descarga de datos de Twitter' },
  { name: 'DumpItBlue+', url: 'https://chrome.google.com/webstore/detail/dumpitblue%2B/igmgknoioooacbcpcfgjigbaajpelbfe/', icon: 'fas fa-download', description: 'Extensión para descargar contenido de redes sociales' },
  { name: 'Encontrar ID de Usuario de Instagram', url: 'https://www.codeofaninja.com/tools/find-instagram-user-id/', icon: 'fab fa-instagram', description: 'Herramienta para encontrar ID de usuarios de Instagram' },
  { name: 'Exportar Comentarios', url: 'https://exportcomments.com/', icon: 'fas fa-comment', description: 'Herramienta para exportar comentarios de redes sociales' },
  { name: 'Exportgram', url: 'https://exportgram.net/', icon: 'fab fa-instagram', description: 'Exportación de datos de Instagram' },
  { name: 'Facebook Graph Searcher', url: 'https://intelx.io/tools?tab=facebook', icon: 'fab fa-facebook', description: 'Buscador avanzado para Facebook' },
  { name: 'Facebook People Search', url: 'https://www.facebook.com/directory/people/', icon: 'fab fa-facebook', description: 'Búsqueda de personas en Facebook' },
  { name: 'FacebookMatrix', url: 'https://plessas.net/facebookmatrix', icon: 'fab fa-facebook', description: 'Herramienta de análisis de datos de Facebook' },
  { name: 'Fansearch', url: 'https://www.fansearch.com/', icon: 'fas fa-users', description: 'Buscador de fans en OnlyFans' },
  { name: 'Fansmetrics', url: 'https://fansmetrics.com/', icon: 'fas fa-chart-bar', description: 'Análisis de métricas de OnlyFans' },
  { name: 'Find Github User ID', url: 'https://caius.github.io/github_id', icon: 'fab fa-github', description: 'Herramienta para encontrar ID de usuarios de GitHub' },
  { name: 'Findr.fans', url: 'https://findr.fans/', icon: 'fas fa-search', description: 'Buscador de perfiles en OnlyFans' },
  { name: 'Foller', url: 'https://foller.me/', icon: 'fab fa-twitter', description: 'Análisis de perfiles de Twitter' },
  { name: 'FollowerWonk', url: 'https://followerwonk.com/bio', icon: 'fab fa-twitter', description: 'Herramienta de análisis de seguidores en Twitter' },
  { name: 'Free People Search Tool', url: 'https://freepeoplesearchtool.com/#gsc.tab=0', icon: 'fas fa-search', description: 'Herramienta gratuita de búsqueda de personas' },
  { name: 'Fulldp', url: 'https://fulldp.co/onlyfans-full-size-profile-picture/', icon: 'fas fa-image', description: 'Descarga de fotos de perfil de OnlyFans' },
  { name: 'Gebruikersnamen: Snapchat', url: 'https://gebruikersnamen.nl/snapchat', icon: 'fab fa-snapchat', description: 'Buscador de nombres de usuario en Snapchat' },
  { name: 'GitGot', url: 'https://github.com/BishopFox/GitGot', icon: 'fab fa-github', description: 'Herramienta OSINT para GitHub' },
  { name: 'Github Dorks', url: 'https://github.com/techgaun/github-dorks', icon: 'fab fa-github', description: 'Técnicas de búsqueda avanzada en GitHub' },
  { name: 'Github Trending RSS', url: 'https://mshibanami.github.io/GitHubTrendingRSS', icon: 'fab fa-github', description: 'RSS de tendencias en GitHub' },
  { name: 'Github Username Search Engine', url: 'https://githubnotes-47071.firebaseapp.com/#/?_k=n0bgxn', icon: 'fab fa-github', description: 'Motor de búsqueda de nombres de usuario en GitHub' },
  { name: 'Hubite', url: 'https://hubite.com/en/onlyfans-search/', icon: 'fas fa-search', description: 'Buscador de perfiles en OnlyFans' },
  { name: 'InSpy', url: 'https://github.com/jobroche/InSpy', icon: 'fab fa-linkedin', description: 'Herramienta OSINT para LinkedIn' },
  { name: 'InstaFreeView', url: 'https://instafreeview.com/', icon: 'fab fa-instagram', description: 'Visor gratuito de perfiles de Instagram' },
  { name: 'Instahunt', url: 'https://instahunt.huntintel.io/', icon: 'fab fa-instagram', description: 'Herramienta OSINT para Instagram' },
  { name: 'Instaloader', url: 'https://github.com/instaloader/instaloader', icon: 'fab fa-instagram', description: 'Herramienta para descargar contenido de Instagram' },
  { name: 'Integraciones IFTTT de Instagram', url: 'https://ifttt.com/instagram', icon: 'fab fa-instagram', description: 'Automatizaciones para Instagram usando IFTTT' },
  { name: 'IntelligenceX Linkedin', url: 'https://intelx.io/tools?tab=linkedin', icon: 'fab fa-linkedin', description: 'Buscador OSINT para LinkedIn' },
  { name: 'La búsqueda ha vuelto', url: 'https://searchisback.com/', icon: 'fas fa-search', description: 'Herramienta de búsqueda para redes sociales' },
  { name: 'LinkedIn Boolean Search', url: 'https://linkedprospect.com/linkedin-boolean-search-tool/#tool', icon: 'fab fa-linkedin', description: 'Búsqueda booleana para LinkedIn' },
  { name: 'LinkedInt', url: 'https://github.com/vysecurity/LinkedInt', icon: 'fab fa-linkedin', description: 'Herramienta OSINT para LinkedIn' },
  { name: 'Linkedin Search Tool', url: 'https://inteltechniques.com/tools/Linkedin.html', icon: 'fab fa-linkedin', description: 'Herramienta de búsqueda para LinkedIn' },
  { name: 'Lookupguru', url: 'https://lookup.guru/', icon: 'fas fa-search', description: 'Buscador de información de perfiles' },
  { name: 'Mavekite', url: 'https://mavekite.com/', icon: 'fas fa-users', description: 'Herramienta para análisis de redes sociales' },
  { name: 'Mostly Harmless', url: 'https://kerrick.github.io/Mostly-Harmless/#features', icon: 'fab fa-github', description: 'Herramienta OSINT para GitHub' },
  { name: 'Network Tool', url: 'https://osome.iu.edu/tools/networks/', icon: 'fas fa-network-wired', description: 'Herramienta para análisis de redes' },
  { name: 'OSINT Combine: Analizador de Publicaciones de Reddit', url: 'https://www.osintcombine.com/reddit-post-analyser', icon: 'fab fa-reddit', description: 'Analizador de publicaciones de Reddit' },
  { name: 'OSINT Combine: Snapchat MultiViewer', url: 'https://www.osintcombine.com/snapchat-multi-viewer', icon: 'fab fa-snapchat', description: 'Visor de múltiples cuentas de Snapchat' },
  { name: 'OnlyFinder', url: 'https://onlyfinder.com/', icon: 'fas fa-search', description: 'Buscador de perfiles en OnlyFans' },
  { name: 'OnlySearch', url: 'https://onlysearch.co/', icon: 'fas fa-search', description: 'Motor de búsqueda para OnlyFans' },
  { name: 'Osintgram', url: 'https://github.com/Datalux/Osintgram', icon: 'fab fa-instagram', description: 'Herramienta OSINT para Instagram' },
  { name: 'Phantom Buster', url: 'https://phantombuster.com/phantombuster?category=reddit', icon: 'fab fa-reddit', description: 'Automatización para Reddit' },
  { name: 'Pickuki', url: 'https://www.picuki.com/', icon: 'fab fa-instagram', description: 'Visor de perfiles de Instagram' },
  { name: 'IMGinn.io', url: 'https://imginn.io/', icon: 'fab fa-instagram', description: 'Descarga de contenido de Instagram' },
  { name: 'Pinterest Guest', url: 'https://addons.mozilla.org/en-US/firefox/addon/pinterest-guest', icon: 'fab fa-pinterest', description: 'Extensión para navegar Pinterest sin cuenta' },
  { name: 'Pinterest Photo Downloader', url: 'https://www.expertsphp.com/pinterest-photo-downloader.html', icon: 'fab fa-pinterest', description: 'Descarga de fotos de Pinterest' },
  { name: 'Programmable Search Engine', url: 'https://cse.google.com/cse?cx=daaf18e804f81bed0', icon: 'fab fa-google', description: 'Motor de búsqueda programable de Google' },
  { name: 'Quién publicó qué', url: 'https://whopostedwhat.com/', icon: 'fas fa-search', description: 'Buscador de publicaciones en redes sociales' },
  { name: 'StalkFace', url: 'https://stalkface.com/en/', icon: 'fab fa-facebook', description: 'Análisis de perfiles de Facebook' },
  { name: 'Readr for Reddit', url: 'https://chrome.google.com/webstore/detail/readr-forreddit/molhdaofohigaepljchpmfablknhabmo', icon: 'fab fa-reddit', description: 'Extensión para mejorar la experiencia en Reddit' },
  { name: 'RecruitEm', url: 'https://recruitin.net/', icon: 'fab fa-linkedin', description: 'Herramienta de reclutamiento en LinkedIn' },
  { name: 'Reddit Enhancement Suite (Complemento de Firefox)', url: 'https://addons.mozilla.org/enGB/firefox/addon/reddit-enhancement-suite', icon: 'fab fa-reddit', description: 'Extensión para mejorar Reddit en Firefox' },
  { name: 'Reddit Enhancement Suite (Extensión de Chrome)', url: 'https://chrome.google.com/webstore/detail/redditenhancementsuite/kbmfpngjjgdllneeigpgjifpgocmfgmb', icon: 'fab fa-reddit', description: 'Extensión para mejorar Reddit en Chrome' },
  { name: 'Reddit Hacks', url: 'https://github.com/EdOverflow/hacks', icon: 'fab fa-reddit', description: 'Trucos y herramientas para Reddit' },
  { name: 'Reddit Search (cemulate)', url: 'https://cemulate.github.io/reddit-search', icon: 'fab fa-reddit', description: 'Buscador personalizado para Reddit' },
  { name: 'Reddit Search (realsrikar)', url: 'https://realsrikar.github.io/reddit-search', icon: 'fab fa-reddit', description: 'Buscador alternativo para Reddit' },
  { name: 'Reddit Search (viralharia)', url: 'https://viralharia.github.io/finddit', icon: 'fab fa-reddit', description: 'Buscador de Reddit personalizado' },
  { name: 'Reddit User Analyser', url: 'https://atomiks.github.io/reddit-user-analyser', icon: 'fab fa-reddit', description: 'Analizador de usuarios de Reddit' },
  { name: 'Reverse Email Lookup', url: 'https://www.reversecontact.com/', icon: 'fas fa-envelope', description: 'Búsqueda inversa de correos electrónicos' },
  { name: 'RocketReach', url: 'https://rocketreach.co/person', icon: 'fas fa-search', description: 'Buscador de contactos profesionales' },
  { name: 'Similarfans', url: 'https://similarfans.com/', icon: 'fas fa-users', description: 'Buscador de perfiles similares en OnlyFans' },
  { name: 'SimpleScraper OSINT', url: 'https://airtable.com/appyDhNeSetZU0rIw/shrceHfvukijgln9q/tblxgilU0SzfXNEwS/viwde4ACDDOpeJ8aO?blocks=bipxY3tKD5Lx0wmEU', icon: 'fas fa-database', description: 'Herramienta de scraping para OSINT' },
  { name: 'Snap Political Ads Library', url: 'https://www.snap.com/en-GB/political-ads', icon: 'fab fa-snapchat', description: 'Biblioteca de anuncios políticos en Snapchat' },
  { name: 'SnapIntel', url: 'https://github.com/Kr0wZ/SnapIntel', icon: 'fab fa-snapchat', description: 'Herramienta OSINT para Snapchat' },
  { name: 'Snapchat-mapscraper', url: 'https://github.com/nemec/snapchat-map-scraper', icon: 'fab fa-snapchat', description: 'Scraper para mapas de Snapchat' },
  { name: 'Social Bearing', url: 'https://socialbearing.com/', icon: 'fab fa-twitter', description: 'Análisis de tweets y perfiles de Twitter' },
  { name: 'Social Searcher', url: 'https://www.social-searcher.com/', icon: 'fas fa-search', description: 'Buscador de contenido en redes sociales' },
  { name: 'Lookup-id.com', url: 'https://lookup-id.com/', icon: 'fab fa-facebook', description: 'Buscador de ID de usuarios de Facebook' },
  { name: 'SocialAnalyzer - Análisis y Sentimiento Social', url: 'https://chromewebstore.google.com/detail/socialanalyzer-social-sen/efeikkcpimdfpdlmlbjdecnmkknjcfcp', icon: 'fas fa-chart-line', description: 'Extensión para análisis de sentimientos en redes sociales' },
  { name: 'SocialData API', url: 'https://socialdata.tools/', icon: 'fas fa-code', description: 'API para datos de redes sociales' },
  { name: 'SolG', url: 'https://github.com/yezz123/SoIG', icon: 'fab fa-instagram', description: 'Herramienta OSINT para Instagram' },
  { name: 'SourcingLab: Pinterest', url: 'https://sourcinglab.io/search/pinterest', icon: 'fab fa-pinterest', description: 'Buscador de contenido en Pinterest' },
  { name: 'Suggest me a subreddit', url: 'https://nikas.praninskas.com/suggest-subreddit', icon: 'fab fa-reddit', description: 'Recomendador de subreddits' },
  { name: 'SóTugas', url: 'https://sotugas.com/', icon: 'fas fa-users', description: 'Plataforma de búsqueda de perfiles' },
  { name: 'Telegram Channels Search', url: 'https://xtea.io/ts_en.html', icon: 'fab fa-telegram', description: 'Buscador de canales de Telegram' },
  { name: 'Telegram Channels', url: 'https://tlgrm.eu/channels', icon: 'fab fa-telegram', description: 'Directorio de canales de Telegram' },
  { name: 'Telegram Scraper', url: 'https://github.com/th3unkn0n/TeleGram-Scraper', icon: 'fab fa-telegram', description: 'Herramienta para scraping de Telegram' },
  { name: 'Telegram-osint-lib', url: 'https://github.com/Postuf/telegram-osint-lib', icon: 'fab fa-telegram', description: 'Biblioteca OSINT para Telegram' },
  { name: 'The Favourite OnlyFans search', url: 'https://onlyfansfinder.co/', icon: 'fas fa-search', description: 'Buscador de perfiles en OnlyFans' },
  { name: 'TikTok Video Downloader', url: 'https://ssstik.io/en-1', icon: 'fab fa-tiktok', description: 'Descarga de videos de TikTok' },
  { name: 'TikTok hashtag analysis toolset', url: 'https://github.com/bellingcat/tiktok-hashtag-analysis', icon: 'fab fa-tiktok', description: 'Análisis de hashtags de TikTok' },
  { name: 'Tinfoleak', url: 'https://tinfoleak.com/', icon: 'fab fa-twitter', description: 'Herramienta OSINT para Twitter' },
  { name: 'Top.gg', url: 'https://top.gg/', icon: 'fab fa-discord', description: 'Directorio de bots y servidores de Discord' },
  { name: 'TweetDeck', url: 'https://tweetdeck.twitter.com/', icon: 'fab fa-twitter', description: 'Interfaz avanzada para Twitter' },
  { name: 'Twitonomy', url: 'https://www.twitonomy.com/', icon: 'fab fa-twitter', description: 'Análisis de estadísticas de Twitter' },
  { name: 'Twitter Advanced Search', url: 'https://twitter.com/search-advanced', icon: 'fab fa-twitter', description: 'Búsqueda avanzada en Twitter' },
  { name: 'Twitter Video Downloader', url: 'https://twittervideodownloader.com/', icon: 'fab fa-twitter', description: 'Descarga de videos de Twitter' },
  { name: 'Twitter search tool', url: 'https://www.aware-online.com/en/osint-tools/twitter-search-tool/', icon: 'fab fa-twitter', description: 'Herramienta de búsqueda para Twitter' },
  { name: 'Universal Reddit Scraper (URS)', url: 'https://github.com/JosephLai241/URS', icon: 'fab fa-reddit', description: 'Scraper universal para Reddit' },
  { name: 'Unofficial Discord Lookup', url: 'https://discord.id/', icon: 'fab fa-discord', description: 'Buscador no oficial de ID de Discord' },
  { name: 'Verificador de enlaces de CrowdTangle', url: 'https://apps.crowdtangle.com/chrome-extension', icon: 'fas fa-link', description: 'Verificador de enlaces para análisis de redes sociales' },
  { name: 'Vizit', url: 'https://redditstuff.github.io/sna/vizit', icon: 'fab fa-reddit', description: 'Visualización de datos de Reddit' },
  { name: 'Wayback Tweets', url: 'https://waybacktweets.streamlit.app/', icon: 'fab fa-twitter', description: 'Archivo de tweets usando Wayback Machine' },
  { name: 'Whatsapp Monitor', url: 'https://github.com/ErikTschierschke/WhatsappMonitor', icon: 'fab fa-whatsapp', description: 'Monitor de actividad de WhatsApp' },
  { name: 'Who posted this', url: 'https://whopostedwhat.com/', icon: 'fas fa-search', description: 'Buscador de publicaciones en redes sociales' },
  { name: '_IntelligenceX: Telegram', url: 'https://intelx.io/tools?tab=telegram', icon: 'fab fa-telegram', description: 'Buscador OSINT para Telegram' },
  { name: 'exolyt', url: 'https://exolyt.com/', icon: 'fab fa-tiktok', description: 'Análisis de perfiles y tendencias de TikTok' },
  { name: 'git-hound', url: 'https://github.com/tillson/git-hound', icon: 'fab fa-github', description: 'Herramienta OSINT para GitHub' },
  { name: 'gitGraber', url: 'https://github.com/hisxo/gitGraber', icon: 'fab fa-github', description: 'Scraper de datos de GitHub' },
  { name: 'informer', url: 'https://github.com/paulpierre/informer', icon: 'fab fa-telegram', description: 'Herramienta OSINT para Telegram' },
  { name: 'instalooter', url: 'https://pypi.org/project/instalooter/', icon: 'fab fa-instagram', description: 'Herramienta para descargar contenido de Instagram' },
  { name: 'instanavigation', url: 'https://instanavigation.com/', icon: 'fab fa-instagram', description: 'Visor anónimo de historias de Instagram' },
  { name: 'memory.lol', url: 'https://memory.lol/app/', icon: 'fab fa-twitter', description: 'Buscador de nombres de usuario antiguos en Twitter' },
  { name: 'smat', url: 'https://www.smat-app.com/timeline', icon: 'fas fa-chart-line', description: 'Análisis de tendencias en redes sociales' },
  { name: 'socid_extractor', url: 'https://github.com/soxoj/socid_extractor', icon: 'fas fa-id-card', description: 'Extracto de IDs de redes sociales' },
  { name: 'telegram-history-dump', url: 'https://github.com/tvdstaaij/telegram-history-dump', icon: 'fab fa-telegram', description: 'Descarga de historial de Telegram' },
  { name: 'toutatis', url: 'https://pypi.org/project/toutatis/', icon: 'fab fa-instagram', description: 'Herramienta OSINT para Instagram' },
  { name: 'tweeterid', url: 'https://tweeterid.com/', icon: 'fab fa-twitter', description: 'Buscador de ID de usuarios de Twitter' },
  { name: 'whatsfoto', url: 'https://github.com/zoutepopcorn/whatsfoto', icon: 'fab fa-whatsapp', description: 'Herramienta OSINT para WhatsApp' },
  { name: 'AddMeSnaps', url: 'https://www.addmesnaps.com', icon: 'fab fa-snapchat', description: 'Plataforma para agregar contactos en Snapchat' },
  { name: 'Awesome Lists', url: 'https://awesomelists.top', icon: 'fas fa-list', description: 'Colección de listas curadas para desarrolladores' },
  { name: 'ChatToday', url: 'https://chattoday.com', icon: 'fas fa-comment', description: 'Plataforma de mensajería y chats' },
  { name: 'CoderStats', url: 'https://coderstats.net', icon: 'fas fa-code', description: 'Estadísticas de desarrolladores en GitHub' },
  { name: 'F5BOT', url: 'https://f5bot.com', icon: 'fas fa-robot', description: 'Bot para monitorear menciones en Reddit y Hacker News' },
  { name: 'GH Archive', url: 'https://www.gharchive.org', icon: 'fab fa-github', description: 'Archivo de eventos de GitHub' },
  { name: 'GhostCodes', url: 'https://www.ghostcodes.com', icon: 'fab fa-snapchat', description: 'Directorio de usuarios de Snapchat' },
  { name: 'Git-Awards', url: 'https://git-awards.com', icon: 'fab fa-github', description: 'Clasificación de usuarios de GitHub' },
  { name: 'GitHut', url: 'https://githut.info', icon: 'fab fa-github', description: 'Visualización de estadísticas de GitHub' },
  { name: 'Github Stars', url: 'https://githubstars.com', icon: 'fab fa-github', description: 'Rastreador de estrellas de repositorios de GitHub' },
  { name: 'Karma Decay', url: 'https://karmadecay.com', icon: 'fab fa-reddit', description: 'Buscador de repost en Reddit' },
  { name: 'Lyzem.com', url: 'https://lyzem.com', icon: 'fas fa-comment', description: 'Plataforma de mensajería social' },
  { name: 'Pingroupie', url: 'https://pingroupie.com', icon: 'fab fa-pinterest', description: 'Buscador de grupos de Pinterest' },
  { name: 'ReSavr', url: 'https://www.resavr.com', icon: 'fab fa-reddit', description: 'Archivo de comentarios eliminados de Reddit' },
  { name: 'Reddit Archive', url: 'https://www.redditarchive.com', icon: 'fab fa-reddit', description: 'Archivo de publicaciones de Reddit' },
  { name: 'Reddit Comment Search', url: 'https://redditcommentsearch.com', icon: 'fab fa-reddit', description: 'Buscador de comentarios en Reddit' },
  { name: 'Reddit List', url: 'https://redditlist.com', icon: 'fab fa-reddit', description: 'Lista de subreddits populares' },
  { name: 'Reddit Search (react-reddit-search-app)', url: 'https://react-reddit-search-app.web.app', icon: 'fab fa-reddit', description: 'Aplicación de búsqueda para Reddit' },
  { name: 'Reddit Search (reddit-search)', url: 'https://reddit-search.surge.sh', icon: 'fab fa-reddit', description: 'Buscador alternativo para Reddit' },
  { name: 'Reddit Search (redditsearch.io)', url: 'https://www.redditsearch.io', icon: 'fab fa-reddit', description: 'Motor de búsqueda para Reddit' },
  { name: 'Reddit Shell', url: 'https://redditshell.com', icon: 'fab fa-reddit', description: 'Interfaz de línea de comandos para Reddit' },
  { name: 'Reddit Stream', url: 'https://reddit-stream.com', icon: 'fab fa-reddit', description: 'Transmisión en tiempo real de publicaciones de Reddit' },
  { name: 'Redditery', url: 'https://www.redditery.com', icon: 'fab fa-reddit', description: 'Herramienta de exploración de Reddit' },
  { name: 'Redective', url: 'https://redective.com', icon: 'fab fa-reddit', description: 'Análisis de perfiles de Reddit' },
  { name: 'Reditr', url: 'https://reditr.com', icon: 'fab fa-reddit', description: 'Cliente alternativo para Reddit' },
  { name: 'Reeddit', url: 'https://reedditapp.com', icon: 'fab fa-reddit', description: 'Aplicación para navegar Reddit' },
  { name: 'Skypli', url: 'https://www.skypli.com', icon: 'fas fa-comment', description: 'Plataforma de mensajería segura' },
  { name: 'Snap Map', url: 'https://map.snapchat.com', icon: 'fab fa-snapchat', description: 'Mapa interactivo de Snapchat' },
  { name: 'SnapInsta', url: 'https://snapinsta.app', icon: 'fab fa-instagram', description: 'Descarga de contenido de Instagram' },
  { name: 'Social Finder', url: 'https://socialfinder.app', icon: 'fas fa-search', description: 'Buscador de perfiles en redes sociales' },
  { name: 'Subreddits', url: 'https://subreddits.org', icon: 'fab fa-reddit', description: 'Directorio de subreddits' },
  { name: 'Tailwind', url: 'https://www.tailwindapp.com', icon: 'fab fa-pinterest', description: 'Herramienta de programación para Pinterest e Instagram' },
  { name: 'Telegram Directory', url: 'https://tdirectory.me', icon: 'fab fa-telegram', description: 'Directorio de grupos y canales de Telegram' },
  { name: 'Telegram Group', url: 'https://www.telegram-group.com', icon: 'fab fa-telegram', description: 'Buscador de grupos de Telegram' },
  { name: 'Tgram.io', url: 'https://tgram.io', icon: 'fab fa-telegram', description: 'Buscador de contenido en Telegram' },
  { name: 'Tgstat RU', url: 'https://tgstat.ru', icon: 'fab fa-telegram', description: 'Estadísticas de canales de Telegram (Rusia)' },
  { name: 'Tgstat.com', url: 'https://tgstat.com', icon: 'fab fa-telegram', description: 'Estadísticas globales de Telegram' },
  { name: 'uforio', url: 'https://uforio.com', icon: 'fab fa-reddit', description: 'Interfaz alternativa para Reddit' },
  { name: 'addmeContacts', url: 'https://add-me-contacts.com', icon: 'fas fa-user-plus', description: 'Plataforma para agregar contactos en redes sociales' },
  { name: 'checkwa', url: 'https://checkwa.online', icon: 'fab fa-whatsapp', description: 'Verificador de cuentas de WhatsApp' },
  { name: 'rdddeck', url: 'https://rdddeck.com', icon: 'fab fa-reddit', description: 'Interfaz avanzada para Reddit' },
  { name: 'redditvids', url: 'https://redditvids.com', icon: 'fab fa-reddit', description: 'Descarga de videos de Reddit' },
  { name: 'reddtip', url: 'https://www.redditp.com', icon: 'fab fa-reddit', description: 'Visor de imágenes y videos de Reddit' },
  { name: 'Wisdom of Reddit', url: 'https://wisdomofreddit.com', icon: 'fab fa-reddit', description: 'Colección de publicaciones destacadas de Reddit' }
]